language: generic 
sudo: required
services: 
    - docker

before_install:
    - docker build -t mfrey777/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mfrey777/react-test npm test

after_success:
    - docker build -t mfrey777/multi-client ./client
    - docker build -t mfrey777/multi-nginx ./nginx
    - docker build -t mfrey777/multi-server ./server
    - docker build -t mfrey777/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push those images to the docker hub
    - docker push mfrey777/multi-client
    - docker push mfrey777/multi-nginx
    - docker push mfrey777/multi-server
    - docker push mfrey777/multi-worker

# deploy:
#     provider: elasticbeanstalk
#     region: "eu-central-1"
#     app: "multi-docker"
#     env: "MultiDocker-env"
#     bucket_name: "elasticbeanstalk-eu-central-1-159117822932"
#     bucket_path: "multi-docker"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY